### PR TITLE
Removed Console/Shell Path - Updated to Just {src}/Shell

### PR DESCRIPTION
**Pull request by jtyost2**
There is no Console/Shell path.

### CODE REVIEW

**Comment by beporter** [comment]
Actually, I was thinking that this should pretty much provide what we'd expect from a Travis run. As an example:

https://github.com/loadsys/EducationUnlimited-Mk2/blob/aae23f832ba59babbdf64ce79480d22674fa3a9c/.travis.yml#L47

```shell
bin/phpcs -p --extensions=php --standard=Loadsys ./src ./plugins ./tests ./config ./webroot
```

That is, provided we have the kinks with scanning .ctp files worked out.

**Comment by jtyost2** [comment]
That's actually my preference.

**Comment by beporter** [comment]
Do you want to add the commit, or should I?

**Comment by jtyost2** [comment]
@beporter go ahead if you want. I'm taking lunch.

**Pull request merged**
