### PR TITLE
Incorporates a code coverage check script.

### PR DESCRIPTION
**Pull request by beporter**
TODO: Should also be added to the 3.0 branch.

### CODE REVIEW

**Comment by ricog** [comment]
:+1: Works here. Thanks!

**Comment by beporter** [comment]
I like the auto-detect option you had though. I'm gonna work on it some more using my own projects to try to make sure it's relatively bulletproof.

**Comment by ricog** [comment]
It's probably not worth it since we can't assume any locations (just like where the script is installed).

**Comment by beporter** [comment]
Well, at least _trying_ to guess seems worthwhile. It just needs to error if it can't read the pnpunit.xml file, can't obtain the path from it, or can't read the path obtained from it.

**Comment by ricog** [comment]
Good point.

**Comment by beporter** [comment]
I'm working on it. **Don't do anything!** lol

**Comment by beporter** [comment]
Okay @ricog, would you like to give this version a try? Note that the argument order is reversed now to make the path to the clover.xml file more easily optional. (The percentage is also now optional, and defaults to 100% for maximum strictness.)

Example calls:

```shell
# Will use Config/pphpunit.xml's <log type="coverage-clover" target="THIS">
# to guess the clover.xml path.
$ bin/coverage-ensure

# 75% coverage instead of default 100%
$ bin/coverage-ensure 75

# Define a manual path (takes precedence over guessing.)
$ bin/coverage-ensure 85 my/own/clover.xml  
```

As noted before, it shouldn't matter where the script itself lives or if it's called via symlink, provided you **do the calling from the project root**. In other words, `getcwd()` must return the path that contains your `README.md`, `composer.json` and `Vagrantfile`, for example.

**Comment by ricog** [comment]
Good work on this @beporter. Thanks! Testing 3.x version next.

**Pull request merged**
