### PR TITLE
F/add phpmetrics

### PR DESCRIPTION
**Pull request by justinyost**
:warning: Work In Progress :warning:

- [x] Add PHPMetrics as a Composer Dependency
- [x] Add Script to run PHPMetrics and Generate Report (wrapper around `./bin/phpmetrics --report-html=./tmp/phpmetrics/index.html ./src`)

### CODE REVIEW

**Comment by justinyost** [comment]
@beporter if you want to take this to finish up the wrapper script feel free.

**Comment by beporter** [comment]
Roger.

**Comment by beporter** [comment]
Please give the new wrapper script a quick once-over. I'm failure sure it has no compile-time errors, but it's hard to test without manually installing the wrapper (and phpmetrics) into a project.

**Comment by justinyost** [comment]
"failure sure" I love that.

**Comment by beporter** [comment]
:stuck_out_tongue:

**Comment by justinyost** [comment]
Looks good here, to test for sure you could do a new branch in EU since there we are on `dev-master` of the shell scripts and just checkout this and such.

**Comment by beporter** [comment]
We'll merge it and give it a shot. The nice thing about adding new scripts is that they don't have any effect on existing behavior, so you can have them in master and tweak them for a while before starting to depend on them.

**Comment by justinyost** [comment]
Verified as working per other project.

**Comment by justinyost** [comment]
I vote tag and release.

**Pull request merged**
